package common.enums;

import java.io.Serializable;

/**
 * Enumeration of reservation-related operations used in request messages.
 */
public enum ReservationOperation implements Serializable  {
    GET_ALL_RESERVATIONS,
    UPDATE_RESERVATION_FIELDS,
    CREATE_RESERVATION,
    CANCEL_RESERVATION,
    GET_CUSTOMER_RESERVATIONS_FOR_CANCELLATION,
    GET_CUSTOMER_RESERVATIONS_FOR_RECEIVING,
    GET_CUSTOMER_RESERVATIONS_FOR_CHECKOUT,
    RESEND_CONFIRMATION_CODE,
    GET_RESERVATION_By_CONFIRMATION_CODE_FOR_CANCELLATION,
    GET_RESERVATION_By_CONFIRMATION_CODE_FOR_RECEIVING,
    GET_RESERVATION_By_CONFIRMATION_CODE_FOR_CHECKOUT,
    JOIN_WAITLIST,
    JOIN_GUEST,WAITLIST,
    RECEIVE_TABLE,
    GET_BILL_FOR_PAYING,
    PAY_BILL
}
