package common.enums;

public enum UserAccountOperation {
	SUBSCRIBER_LOG_IN,
	EMPLOYEE_LOG_IN,
    LOGGED_IN_STATUS,
    LOGOUT,
    REGISTER_SUBSCRIBER,
    GET_SUBSCRIBER_PROFILE,
    LOOKUP_CUSTOMER_BY_SUBSCRIPTION_CODE,
    LOOKUP_CUSTOMER_BY_PHONE,
    LOOKUP_CUSTOMER_BY_EMAIL,
    UPDATE_SUBSCRIBER_PROFILE,
    GET_ALL_SUBSCRIBERS,
    GET_CURRENT_DINERS
}
